#ifndef DataConstants_h
#define DataConstants_h

/**
 Background queue ID for Core Data handling
 */
#define COREDATA_BG_QUEUE_ID "coredata.bgsavequeue"

/**
 Background queue ID for cache manager
 */
#define CACHEMANAGER_BG_QUEUE_ID "cachesmanager"

/**
 Error domain for callbacks supplied in DataManager
 */
#define DATAMANAGER_ERRORDOMAIN @"datamanager"



#define USERIDENTITY_UNIQUE_ID @"USERIDENTITY_UNIQUE_ID"
#define USERIDENTITY_DISPLAY_NAME @"USERIDENTITY_DISPLAY_NAME"
#define USERIDENTITY_LEVEL @"USERIDENTITY_LEVEL"
#define USERIDENTITY_LOCAL_CITY @"USERIDENTITY_LOCAL_CITY"
#define USERIDENTITY_IS_MALE @"USERIDENTITY_IS_MALE"
#define USERIDENTITY_FOLLOW_COUNT @"USERIDENTITY_FOLLOW_COUNT"
#define USERIDENTITY_FANS_COUNT @"USERIDENTITY_FANS_COUNT"
#define USERIDENTITY_COLLECTION_COUNT @"USERIDENTITY_COLLECTION_COUNT"
#define USERIDENTITY_BUYED_COUNT @"USERIDENTITY_BUYED_COUNT"
#define USERIDENTITY_TOPIC_COUNT @"USERIDENTITY_TOPIC_COUNT"
#define USERIDENTITY_BLACK_LIST_COUNT @"USERIDENTITY_BLACK_LIST_COUNT"
#define USERIDENTITY_PERSONAL_BRIEF @"USERIDENTITY_PERSONAL_BRIEF"
#define USERIDENTITY_DETAILED_ADDRESS @"USERIDENTITY_DETAILED_ADDRESS"


#endif

/** @} */
